### ISSUE TITLE
HR Dashboard-Employee Profiles: Message is not fully displayed in the page. 

### ISSUE THREAD

**Issue by laichiun** [shahrul91/csileavemanagementsystem#153] opened 2019-03-13 07:15 UTC
**Module:** HR Dashboard - Employee Profiles
**Issues:**  Message "Please download the latest Employee Profile Upload Template for you to fill in the data." is not fully displayed in the page.

![image](https://user-images.githubusercontent.com/48428855/54259920-4966c080-45a2-11e9-81ed-6b6e16497c92.png)

**Comment by laichiun** [comment] 2019-03-14 03:08
Additional impact module:
1. HR Dashboard - Leave Entitlement - Upload Leave Entitlement
![image](https://user-images.githubusercontent.com/48428855/54328445-e4b27100-4648-11e9-94e7-7c211ce6ca2f.png)

2, HR Dashboard - Public Holidays - Upload Public Holidays
![image](https://user-images.githubusercontent.com/48428855/54328538-3a871900-4649-11e9-8d58-d19514a46499.png)

**Comment by netkiko** [comment] 2019-03-18 00:19
This is not a bug, the link is still there, it happens when the user clicked on the link to download the template, the link changes color to white that's why it isn't visible but it showed up upon mouse over. As fix of this, I created a dedicated CSS reference for all templates link, so it won't share CSS reference with links seen on the Sidebar menu.

**Comment by syazanajaafar** [comment] 2019-03-21 05:25
Now able to view the link after the fix. Hence will close this issue.

![Invisible links_fixed](https://user-images.githubusercontent.com/48428869/54734739-b3075000-4bdc-11e9-995b-585c21a24b76.PNG)

**Closed by syazanajaafar** 2019-03-21 05:25 UTC
Labels: bug
